---

- name: Symfony2 | Remove old releases
  become: yes
  become_method: sudo
  shell: ls -dr {{ symfony2_root }}/releases/* | tail -n +{{ symfony2_releases + 1 }} | xargs rm -fr
  when: symfony2_releases is defined and symfony2_releases > 0
