---

- name: Symfony2 | Console | Run comands
  shell: >
    cd {{ symfony2_release_root }} && {{ symfony2_php_path }} {{ symfony2_console_path }} {{ item.command|default(item) }} --env={{ symfony2_environment }} {{ symfony2_console_options }} {{ item.options|default('') }}
  with_items: symfony2_console_commands
  when: symfony2_console_commands != false
