---

- include: deploy-git.yml
  when: "'git' == symfony2_deploy_strategy"

- include: deploy-mercurial.yml
  when: "'mercurial' == symfony2_deploy_strategy"

- include: deploy-svn.yml
  when: "'svn' == symfony2_deploy_strategy"

- include: deploy-rsync.yml
  when: "'rsync' == symfony2_deploy_strategy"
