---

- name: Symfony2 | Deploy | Git | Pull sources from the repository
  git:
    repo: "{{ symfony2_repo }}"
    dest: "{{ symfony2_root }}/releases/{{ symfony2_release }}"
    version: "{{ symfony2_branch }}"
    force: yes
  ignore_errors: true
  register: symfony2_deployed
