---

- name: Symfony2 | Deploy | Git | Pull sources from the repository
  git:
    repo: "{{ symfony2_repo }}"
    dest: "{{ symfony2_root }}/releases/{{ symfony2_release }}"
    version: "{{ symfony2_branch }}"
    force: yes
    depth: "{{ symfony2_repo_depth }}"
    key_file: "{{ symfony2_key_file }}"
    accept_hostkey: "{{ symfony2_repo_accept_hostkey }}"
  ignore_errors: "{{ symfony2_repo_ignore_errors }}"
  register: symfony2_deployed
