---

- name: Symfony2 | Deploy | Rsync | Synchronize
  synchronize:
    src: "{{ symfony2_local_root }}"
    dest: "{{ symfony2_release_root }}"
    rsync_opts: "{{ symfony2_rsync_options|default('') }}"
    times: no
    recursive: yes
    perms: no
    owner: no
    group: no
  ignore_errors: true
  register: symfony2_deployed
