---

# @todo Make acceptable variant

- name: Symfony2 | Permissions | Apply for cache/logs
  shell: >
    chown -Rf www-data:www-data {{ symfony2_root }}

- name: Symfony2 | Set logs folders permissions
  shell: >
    chmod -Rf 0777 {{ symfony2_shared_root }}/app/logs
