---

- name: Symfony2 | Release | Get date
  shell: >
    TZ=UTC date +{{ symfony2_release_format }}
  register: release_date
  when: "'' == symfony2_release"

- name: Symfony2 | Release | Set release
  set_fact:
     symfony2_release: "{{ release_date.stdout }}"
  when: "'' == symfony2_release"
