---

- name: Symfony2 | Get date
  shell: >
    date +{{ symfony2_release_format }}
  register: release_date
  when: symfony2_release is not defined

- name: Symfony2 | Set release
  set_fact:
     symfony2_release: "{{ release_date.stdout }}"
  when: symfony2_release is not defined
